services:
  accounts:
    image: "dedpixta2/accounts-service:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - microservices
  loan:
    image: "dedpixta2/loans-service:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - microservices
  cards:
    image: "dedpixta2/cards-service:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - microservices
networks:
  microservices:
      driver: bridge
