server:
  port: 8071

spring:
  application:
    name: config-server
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/config
#          search-locations: "/Users/maxim/Work/education/projects/microservices-own/accounts/config-server/src/main/resources/config"
        git:
          uri: https://github.com/DedPixta/accounts-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "NP8ZTSXLRF9537YKM6CJDQ"